### ISSUE TITLE
Potential memory leak in ExpiringPool

### ISSUE THREAD

**Issue by andrei-l** [andrebeat/scala-pool#11]
Within the ExpiringPool there is a Timer object which creates a daemon thread underneath. 
`private[this] val timer = new Timer(s"scala-pool-${ExpiringPool.count.getAndIncrement}", true)`
In webapp for example this will not allow application which uses this pool to be Garbage Collected normally.

Unfortunately right now there are no means to release this thread. I would suggest to add some `close()` method for a pool which delegate to 'timer.cancel()'

**Comment by andresilva** [comment]
Hi Andrei,

Yes, I agree with you that the pool should provide a `close()` method which in the case of the `ExpiringPool` would shut down the internal `Timer`. I'll add this today (hopefully 😁).

**Comment by andresilva** [comment]
I just opened a PR to implement this and I've also updated the latest SNAPSHOT. Could you try it out and let me know if it works for you?

**Comment by andrei-l** [comment]
Hi Andre,

I looked though sources and tried you latest snapshot - all works as expected, thanks!

**Comment by andresilva** [comment]
Thanks. I released a stable version.
